service: intelligent-interview-system

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.11

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'

resources:
  Resources:
    IntelligentInterview:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

plugins:
  - serverless-wsgi
  - serverless-python-requirements